# Site settings
title: I'm James
tagline: Developer's Blog
email: hello@imjames.me
description: I'm a front-end developer & content manager based in the South-West of England.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://imjamesdotme.github.io/" # the base hostname & protocol for your site

# Social
github_username: imjamesdotme
linkedin_username: jameslilliott

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty
